%% load data files and pool across days
%
% -------------------
% Jeff Mohl
% 5/29/18
% -------------------
%
% Description: function loads tidy data files for a given number of days
% (randomly selected, with the option for a seed) and concatenate them into
% a single data table.

function data = load_pool_data(n_pooled_days,subject,seed)

file_name = sprintf('/%s*AVD2*.mat',subject);
data_dir = dir(['data' file_name]);

if nargin == 3
    rng(seed) %set seed if given
end

rand_days = randsample(length(data_dir),length(data_dir));
data = [];
i=1;
j=1;
while i<n_pooled_days
    load(data_dir(rand_days(j)).name); %will be named tidy_data
    j=j+1;
    if exist('this_tidy')
        tidy_data = this_tidy; %bug in some of the data files that were generated by hand has the data structure mislabeled
    end
    %check that there are sufficient number of trials per condition
    A_data = tidy_data(strcmp(tidy_data.trial_type,'A'),:);
    V_data =tidy_data(strcmp(tidy_data.trial_type,'V'),:);
    AV_data =tidy_data(strcmp(tidy_data.trial_type,'AV'),:);
    gA = findgroups(A_data.A_tar);
    gV = findgroups(V_data.V_tar);
    gAV = findgroups(AV_data(:,{'A_tar','V_tar'}));
    
    A_counts = histc(gA,unique(gA));
    V_counts = histc(gV,unique(gV));
    AV_counts = histc(gAV,unique(gAV));
    % if min trial count is 5, include, otherwise loop again
    if min([A_counts;V_counts;AV_counts]) > 4
        data=[data;tidy_data];
        i=i+1;
    end
    if j > length(rand_days)
        error('Not enough days with sufficient trial counts to pool');
    end
end

end